<a href="https://colab.research.google.com/github/arjunsivakumar24/numpy_document/blob/main/numpy_doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy documentation
# 1. numpy -> numeric python

In [ ]:
# python list
list1=['arjun',24,'cse',True,19.5]
print(*list1)

arjun 24 cse True 19.5


In [ ]:

# ndarray -> n dimensional array
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
# arrange function
arr2=np.arange(10)
print(arr2)

# with step value
arr3=np.arange(10,20,2)
print(arr3)


[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]


In [ ]:
# zeros function
# 1 dimension
arr4=np.zeros(5)
print(arr4)

# n dimension
arr5=np.zeros((2,5))
print(arr5)



[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# full function
# 1 dimension
arr6=np.full((5),6)
print(arr6)
# n dimension
arr7=np.full((2,5),7)
print(arr7)


[6 6 6 6 6]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
# python list to numpy array
list2=[2,4,6,8,9]
arr8=np.array(list2)
print(arr8)

[2 4 6 8 9]


In [ ]:
#2. slicing numpy array
# same as python slicing


In [ ]:
# slicing 1 dimensional array
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
# return 2,3,4,5
print(arr1[1:5])
# return till end
print(arr1[5:])
# return starting to fixed end
print(arr1[:5])
# return step
print(arr1[::2])
# negative slicing
print(arr1[-3:-7:-1])

[2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[1 3 5 7 9]
[8 7 6 5]


In [ ]:
# slicing 2 dimensional array
# length must be same
arr2=np.array([
    [1,2,3,4,5],
     [6,7,8,9,10]])
print(arr2[1])
# slicing a 2-d array
print(arr2[0:2,2])
print(arr2[:,1:3])

[ 6  7  8  9 10]
[3 8]
[[2 3]
 [7 8]]


In [ ]:
# 3.numpy function


In [ ]:
# square root
arr1=[4,9,16,25]
print(np.sqrt(arr1))

[2. 3. 4. 5.]


In [ ]:
# absolute value -> change to positive value
arr2=[-1,2,3,4,-5]
print(np.absolute(arr2))

[1 2 3 4 5]


In [ ]:
# min/max
print(np.min(arr2))
print(np.max(arr2))

-5
4


In [ ]:
# exponent
print(np.exp(arr1))

[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]


In [ ]:
# sign positive or negative
print(np.sign(arr2))

[-1  1  1  1 -1]


In [ ]:
# trig sin cos log
print(np.sin(arr2))

[-0.84147098  0.90929743  0.14112001 -0.7568025   0.95892427]


In [ ]:
# mean
print(np.mean(arr2))
# medium
print(np.median(arr2))
# average
print(np.average(arr2))
# variance
print(np.var(arr2))
# standard deviation
print(np.std(arr2))

0.6
2.0
0.6
10.639999999999999
3.261901286060018


In [ ]:
# 4.copy / view

In [ ]:
arr2=np.array([1,2,3,4,5])
# copy
arr3=arr2.copy()
print(arr3)
arr3[1]=20
print(arr3)
print(arr2)
# view
arr4=arr2.view()
print(arr4)
arr4[2]=10
print(arr4)
print(arr2)


[1 2 3 4 5]
[ 1 20  3  4  5]
[1 2 3 4 5]
[1 2 3 4 5]
[ 1  2 10  4  5]
[ 1  2 10  4  5]


In [ ]:
# 5.shape and reshape

In [ ]:
# 1D shape
np1=np.array([1,2,3,4,5,6,7,8])
print(np1.shape)

# 2D shape
np2=np.array([[1,2,3,4],[5,6,7,8]])
print(np2.shape)

# 3D
np3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(np3.shape)
print(np3)

# reshape

np4=np1.reshape(2,4)
print(np4)
print()
np5=np1.reshape(2,2,2)
print(np5)

# flatten
np6=np5.flatten()
print(np6)

np7=np5.ravel()
print(np7)

np8=np4.reshape(-1)
print(np8)


(8,)
(2, 4)
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [ ]:
# 6.iteration of numpy array

In [ ]:
# 1D
np1=np.array([1,2,3,4,5,6,7,8,9])
for x in np1:
  print(x)
print()
# 2D
np2=np.array([[2,3,4,5,6],[7,8,9,10,11]])
for x in np2:
  for y in x:
    print(y)
print()
# 3D
np3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for i in np3:
  for j in i:
    for k in j:
      print(k)
print()
# using nditer
for x in np.nditer(np3):
  print(x)
print()


1
2
3
4
5
6
7
8
9

2
3
4
5
6
7
8
9
10
11

1
2
3
4
5
6
7
8

1
2
3
4
5
6
7
8



In [ ]:
# 7.sorting

In [ ]:
# 1D
np1=[5,6,3,4,8,2,1]
print(np.sort(np1))

# 2D
np2=[[5,3,2,6],[9,7,0,1]]
print(np.sort(np2))
np3=np.array([5,3,2,6])
np3.sort()
print(np3)


[1 2 3 4 5 6 8]
[[2 3 5 6]
 [0 1 7 9]]
[2 3 5 6]


In [ ]:
# 8.searching -> using where

In [ ]:
# 1D
np1=np.array([1,2,3,4,5,6,7,8,4])
x=np.where(np1 == 4)
print(x)
print(x[0])
print(np1[x[0]])
print()
# 2D
np2=np.array([[1,2,3,5],[9,6,7,8]])
x=np.where(np2 ==5)
print(x[0])
print()

# Boolean indexing
np3=np3[np3 > 5]
print(np3)

(array([3, 8]),)
[3 8]
[4 4]

[0]

[6 7 8]


In [ ]:
# 9.Filter

In [ ]:
# 1D
np1=np.array([1,2,3,4,5,6,7,8])
mask=np1 > 5
filter_arr=np1[mask]
print(filter_arr)

# one line
filter_arr=np1[np1 > 5]
print(filter_arr)
print()

[6 7 8]
[6 7 8]

